### ISSUE TITLE
Emit events

### ISSUE THREAD

**Issue by steve-rodrigue** [norunners/vue#31]
I’m working with your library on a web project.  I need to emit an event and catch it in a parent module.

It looks like the $emit feature has not been implemented yet: https://vuejs.org/v2/guide/components-custom-events.html

If I’m not mistaken, I’d like to implement it and send you a pull request.  Do you accept pull requests?

If it has been implemented and I missed it, kindly point me in the right direction.

Thanks in advance!
Steve

**Comment by steve-rodrigue** [comment]
Nevermind.  I just discovered the callback in the component: https://github.com/norunners/vue/blob/master/callback.go

You can close this issue.

Thanks!

**Comment by norunners** [comment]
Although I have come across documentation of using vue as an event bus, it is not explicitly implemented yet. I'd like to hear more about your use case to see if it makes sense to implement or there is another idiomatic Go way to satisfy the use case.

**Comment by norunners** [comment]
I'm reopening this as a core feature to support. Emitting custom event's is an important part of vue. This feature allows parent component's to listen to custom events dispatched from child components. In addition, it allows optional arguments to be passed along in the custom event. Alternatively, this behavior can be achieved by passing callback functions from parent components down to child components as props. However, emitting custom events appears to be a simpler user experience that satisfies the same requirement.

https://vuejs.org/v2/guide/components-custom-events.html
